services:
  evolution-api:
      container_name: evolution_api
      image: atendai/evolution-api:v2.2.3
      restart: always
      depends_on:
        redis:
          condition: service_started
        # postgres:
        #   condition: service_healthy
      ports:
        - 8080:8080
      volumes:
        - evolution_instances:/evolution/instances
      networks:
        - evolution-net
      env_file:
        - .env
      expose:
        - 8080

  redis:
    image: redis:alpine
    networks:
      - evolution-net
    container_name: redis
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.1'     # Limita a 10% de um núcleo de CPU
          memory: 64M     # Limita a 64MB de Memória RAM
        reservations:
          cpus: '0.05'    # Garante 5% de um núcleo de CPU
          memory: 32M     # Garante 32MB de Memória RAM
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'     # Limita a 50% de um núcleo de CPU
          memory: 512M    # Limita a 512MB de Memória RAM
        reservations:
          cpus: '0.2'     # Garante 20% de um núcleo de CPU
          memory: 256M   # Garante 256MB de Memória RAM
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d evolution"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  evolution-net:  
    name: evolution-net
    driver: bridge

volumes:
  evolution_redis:
  postgres_data:
  evolution_instances: